tools:
    shell:
        allow:
            - ls *
            - find *
            - head *
            - echo *
            - grep *
            - sort
            - git status *
            - awk *
            - uniq *
            - wc *'
            - wc *
            - '[ *'
            - pnpm lint
            - tail *
            - pnpm type-check
